### ISSUE TITLE
Implementation in Julia focusing more accurate and precise mathematical output instead of a Realtime visualization.

### ISSUE THREAD

**Issue by chathura-de-silva** [chathura-de-silva/Barnsley-Fractal#1]
* This repository contains only a simple single script python project. Converting this implementation into `Julia language` is the requirement.  
>[!NOTE]
>You don't have to have prior knowledge about the "Barnsley Fractal" for this. 

* You can go through the documentation provided in the README and get the idea very easily about the current `python` script. 

* Additional functionalities are always welcome and the minor alterations due to limited resources depending on the language is complete fine.
* Focus more on precise plot and tweaks to observe the mathematical perspective more, rather than a limited resolution Realtime plot. 

__PS :  No need to recreate documentation!__ 
 

 What you have to refer : [barnsley_fractal.py](https://github.com/chathura-de-silva/Barnsley-Fractal/blob/main/barnsley_fractal.py)

 Documentation for the current Python implementation : [README.md](https://github.com/chathura-de-silva/Barnsley-Fractal#readme)
 
![issues banner for barnsley fern](https://github.com/chathura-de-silva/Barnsley-Fractal/assets/97898278/acf2b0a8-75ee-4eca-947d-65229caae898)

**Comment by SasikaA073** [comment]
.
